export function showgoods(){
  const showgoods = [
    {
      id:1,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:2,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },{
      id:3,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:4,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:5,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:6,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:7,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:8,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:9,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:10,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:11,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    },
    {
      id:12,
      title:'在项目构建模式方面，将抛弃传统的MVC模式，采用MVVM模式。传统的MVC模式中，M是模型',
      price:123,
      shoucang:1313,
      src:require('@/assets/imgs/tempshouyeswiper/5.png'),
      oldprice:298.00,
      swiper:[
        {
          id:1,
          src:require('@/assets/imgs/tempshouyeswiper/1.png'),
        },
        {
          id:2,
          src:require('@/assets/imgs/tempshouyeswiper/2.png'),
        },
        {
          id:3,
          src:require('@/assets/imgs/tempshouyeswiper/3.png'),
        },
        {
          id:4,
          src:require('@/assets/imgs/tempshouyeswiper/4.png'),
        }
      ]
    }
  ]

  return showgoods
}